### ISSUE TITLE
add a command option so that when globbing, only process files of a particular FPS

### ISSUE THREAD

**Issue by millerthegorilla** [Breakthrough/DVR-Scan#102]
**Description of Problem & Solution**
currently when globbing, some files are at 10pfs and others are at 20fps.  Currently the first appended video sets the correct framerate for processing, and this is reflected in an error message as mp4s are appended, something along the lines of 'warning, framerate wrong' (dvr-scan is in the middle of an overnight scan, and I don't want to risk interrupting it, by processing the same directory for the correct error).
It would be nice if I could add a commandline option when globbing so that files could only be appended if they match the framerate specified to the command option.
Something like
```
dvr-scan -f 10 -i ./**/* -o ../output
```

**Media Examples:**
Where possible, provide videos/images demonstrating the problem at hand or issue you would like to solve (even YouTube links are fine).

**Proposed Implementation:**
It would be nice if I could add a commandline option when globbing so that files could only be appended if they match the framerate specified to the command option.
Something like
```
dvr-scan -f 10 -i ./**/* -o ../output
```

**Alternative Solutions:**
a bash for loop to find files that are at 10fps using ffprobe, and then running dvr-scan on them.
```
FPS=10
for file in $(find . -type f -name "*mp4"); do   if [[ $(ffprobe $file 2>&1| grep ",* fps" | cut -d "," -f 5 | cut -d " " -f 2) == $FPS ]]; then     dvr-scan -bb --threshold 1.5 -i $file -d ../output/ ; fi; done
```

**Comment by Breakthrough** [comment]
Hi @millerthegorilla;

Firstly, thank you for the well thought out proposal.  Unfortunately I must reject this feature request for the following reasons:

- I don't think DVR-Scan should do any kind of selection of what videos should be processed - in my opinion, it should scan exactly the paths passed to `--input` (or those that the input glob matches)
- There could be other options a user might want to filter on, e.g. only scan videos with a resolution of X times Y pixels, which although reasonable, can lead to bloat of the command line arguments
- There exists sufficient workarounds to achieve the desired functionality as you pointed out, and a similar thing could be done natively in Python if required
    - I think your workaround is actually the most correct solution, as it also addresses the previous point about filtering with additional parameters
    - It should be possible to achieve concatenation of inputs, e.g. invoking DVR-Scan only once, with a list of filtered input files, both in Bash and from Python

Thank you for the feature request.  Please feel free to continue the discussion if you disagree, or if something in the future changes to warrant revisiting this.
