### ISSUE TITLE
Export clip in MP4 video format.

### ISSUE THREAD

**Issue by xenio** [Breakthrough/DVR-Scan#11]
Is it possible to export the clip with motion in mp4 format?
I am on MacOS and managing avi file is not so good :(

**Comment by xenio** [comment]
Looks like it is already in mp4 format with avi container.
I just changed the source code to name the clips .mp4 and it is working ok.

**Comment by Breakthrough** [comment]
This will be supported in the future when DVR-Scan is merged with PySceneDetect, as PySceneDetect allows for re-encoding the output video with `ffmpeg`.  Thank you!
