### ISSUE TITLE
Error: Unsupported config option: opencv-fourcc in 1.5.1

### ISSUE THREAD

**Issue by vaskokj** [Breakthrough/DVR-Scan#112]
**Bug/Issue Description:**

Installed dvr-scan with:

`RUN pip install --upgrade dvr-scan[opencv]`

running `dvr-scan -i /tmp/video.mp4 -d /tmp/output -c /opt/project/dvr-scan.cfg`
Get the following error.
```
[DVR-Scan] DVR-Scan v1.5.1
[DVR-Scan] Loading config from file:
  /opt/project/dvr-scan.cfg
[DVR-Scan] Unsupported config option: opencv-fourcc
[DVR-Scan] Failed to load configuration file.
```

Contents of the `dvr-scan.cfg` file:

>$cat /opt/project/dvr-scan.cfg 
>opencv-fourcc = XVID

Do I have to include other parameters? 
**Required Information:**

Provide a full copy of the command line options you are using, and add `--verbosity debug`, for example:

`dvr-scan -i /tmp/video.mp4 -d /tmp/output -c /opt/project/dvr-scan.cfg`

**Expected Behavior:**
Would expect dvr-scan to start processing file. 

**Computing Environment:**
 - OS: [e.g. Windows, Linux (Distro: Ubuntu, Mint, Fedora, etc...), OSX]: Ubuntu 20.04
 - Python Version: [e.g. 3.6 or 3.6.6] 3.8.13
 - OpenCV Version: [e.g. 3.4.1]

**Comment by Breakthrough** [comment]
Looks like the documentation for this is wrong, the actual config is named `opencv-codec`.  I renamed it to be more generic, but seem to have missed updating the documentation.

Sorry about that, try to setting `opencv-codec` instead and I'll use this issue to track fixing the docs.  Thanks for the report.
