### ISSUE TITLE
Report name of corrupt file and continue

### ISSUE THREAD

**Issue by 9812ga98sd** [Breakthrough/DVR-Scan#126]
It would be a good idea to report the name of the corrupt file it cannot read, then output the name or copy it to a folder and then continue processing.

Right now I have to manually stop and start over 49500 files if it finds a corrupt file. 

dvr-scan -i *.mp4 -d output/ -b MOG2_CUDA

Windows 10

"[DVR-Scan] Check that the given file is a valid video clip, and ensure all required dependencies are installed and configured properly.
[DVR-Scan] Failed to load input: isOpened() returned False for 2021-09-13_18-14-28.mp4!"

**Comment by Breakthrough** [comment]
One problem with this is that it may cause a motion event to be detected if the lighting changes significantly.  I suppose this is probably acceptable for most use cases though if only a few are corrupt, and can add a warning that the result might not be accurate if a video was skipped.

I'll work on adding a new option for this in the next release.

**Comment by Breakthrough** [comment]
Sorry I may have misunderstood your use case here.  Can you clarify what you mean by stop and start over?  The program should abort as soon as this occurs, rather than in the middle of a run.  Thanks!

**Comment by abdullahfarwees** [comment]
@9812ga98sd @Breakthrough 
 It sounds like you're looking to differentiate between files processed by "dvr-scan" and those that aren't. You could generate a report or log containing the list of processed filenames for the user's reference. This way, the user can review the report later to see which files were processed by the software.

**Comment by Breakthrough** [comment]
I can add a config file option in v1.6 for this to let corrupt videos be skipped, which will print out a warning instead of stopping the command.
