### ISSUE TITLE
Please return exit code to indicate whether events were detected

### ISSUE THREAD

**Issue by reubenfirmin** [Breakthrough/DVR-Scan#128]
**Description of Problem & Solution**

Please use exit codes to indicate whether or not events were detected. I would like to automate passing different parameters into dvr_scan to calibrate against sample videos, but I have nothing to test against.

Perhaps (bash friendly):

0 for event
1 for no event

**Comment by Breakthrough** [comment]
This was brought up in #96 previously.  You probably want to use string searching from the output to determine this info, not the exit code itself.  If you are so inclined, you could write a wrapper script/program for this purpose as well.  Thanks.
