### ISSUE TITLE
Process ends early and displays error: Element exceeds containing master element

### ISSUE THREAD

**Issue by yasavvym8** [Breakthrough/DVR-Scan#142]
**Bug/Issue Description:**

When trying to process an MKV video that is 15 hours 30 minutes and 32 seconds long, the process for this video ends early, displaying the following output:

Detected: 129 | Progress:  64%|█▉ | 2136077/3349949 [3:03:53<1:42:09, 198.05 frames/s][matroska,webm @ 000001b455c32f80] Element at 0x6131a157d ending at 0x61e5560fa exceeds containing master element ending at 0x6131cc861
[matroska,webm @ 000001b455c32f80] Length 6 indicated by an EBML number's first byte 0x05 at pos 26572929378 (0x62fdeb962) exceeds max length 4.
[matroska,webm @ 000001b455c32f80] 0x00 at pos 27019643992 (0x64a7f0c58) invalid as first byte of an EBML number
[matroska,webm @ 000001b455c32f80] Length 6 indicated by an EBML number's first byte 0x06 at pos 27616049945 (0x66e0b7b19) exceeds max length 4.
Truncating packet of size 183771195 to 9250259
Detected: 129 | Progress:  64%|█▉ | 2136116/3349949 [3:04:05<1:44:36, 193.39 frames/s]
[DVR-Scan] Processed 2136116 frames read in 11046.1 secs (avg 193.4 FPS).
[DVR-Scan] Detected 129 motion events in input.
[DVR-Scan] List of motion events:

-------------------------------------------------------------
|   Event #    |  Start Time  |   Duration   |   End Time   |
-------------------------------------------------------------
|  Event    1  |  01:58:16.0  |  00:00:05.0  |  01:58:20.9  |
|  Event    2  |  01:58:24.1  |  00:00:06.7  |  01:58:30.8  |
|  Event    3  |  02:00:03.7  |  00:00:05.7  |  02:00:09.4  |
|  Event    4  |  02:00:12.1  |  00:00:04.3  |  02:00:16.4  |
|  Event    5  |  03:23:19.9  |  00:00:03.7  |  03:23:23.5  |
|  Event    6  |  03:30:30.6  |  00:00:04.7  |  03:30:35.3  |
|  Event    7  |  04:00:16.9  |  00:00:03.9  |  04:00:20.7  |
|  Event    8  |  04:17:48.6  |  00:00:04.3  |  04:17:52.9  |
|  Event    9  |  07:28:26.5  |  00:00:10.2  |  07:28:36.7  |
|  Event   10  |  07:28:36.7  |  00:00:04.0  |  07:28:40.7  |
|  Event   11  |  07:28:41.1  |  00:00:04.5  |  07:28:45.6  |
|  Event   12  |  07:38:14.0  |  00:00:12.9  |  07:38:27.0  |
|  Event   13  |  08:21:07.0  |  00:00:04.0  |  08:21:11.0  |
|  Event   14  |  08:21:13.0  |  00:00:05.1  |  08:21:18.1  |
|  Event   15  |  08:21:29.0  |  00:00:05.1  |  08:21:34.1  |
|  Event   16  |  08:21:36.0  |  00:00:05.6  |  08:21:41.6  |
|  Event   17  |  08:21:42.0  |  00:00:03.7  |  08:21:45.7  |
|  Event   18  |  08:21:49.1  |  00:00:10.6  |  08:21:59.7  |
|  Event   19  |  08:21:59.8  |  00:00:13.0  |  08:22:12.8  |
|  Event   20  |  08:22:16.5  |  00:00:06.2  |  08:22:22.7  |
|  Event   21  |  08:22:22.8  |  00:00:09.6  |  08:22:32.4  |
|  Event   22  |  08:22:46.2  |  00:00:08.7  |  08:22:54.9  |
|  Event   23  |  08:23:10.5  |  00:00:05.8  |  08:23:16.4  |
|  Event   24  |  08:23:25.0  |  00:00:07.6  |  08:23:32.7  |
|  Event   25  |  08:23:32.7  |  00:00:04.2  |  08:23:36.8  |
|  Event   26  |  08:23:49.9  |  00:00:03.6  |  08:23:53.5  |
|  Event   27  |  08:23:53.5  |  00:00:03.2  |  08:23:56.7  |
|  Event   28  |  08:24:46.2  |  00:00:04.4  |  08:24:50.6  |
|  Event   29  |  08:25:04.7  |  00:00:04.4  |  08:25:09.1  |
|  Event   30  |  08:25:27.5  |  00:00:04.1  |  08:25:31.7  |
|  Event   31  |  08:25:56.0  |  00:00:03.8  |  08:25:59.8  |
|  Event   32  |  08:26:27.3  |  00:00:04.4  |  08:26:31.7  |
|  Event   33  |  08:26:55.5  |  00:00:03.9  |  08:26:59.4  |
|  Event   34  |  08:27:36.1  |  00:00:06.0  |  08:27:42.1  |
|  Event   35  |  08:28:21.2  |  00:00:05.0  |  08:28:26.2  |
|  Event   36  |  08:28:34.5  |  00:00:03.7  |  08:28:38.1  |
|  Event   37  |  08:29:23.0  |  00:00:04.0  |  08:29:27.0  |
|  Event   38  |  08:29:28.5  |  00:00:04.8  |  08:29:33.3  |
|  Event   39  |  08:29:34.7  |  00:00:04.4  |  08:29:39.1  |
|  Event   40  |  08:29:39.1  |  00:00:02.3  |  08:29:41.5  |
|  Event   41  |  08:30:01.5  |  00:00:04.0  |  08:30:05.6  |
|  Event   42  |  08:30:12.2  |  00:00:04.0  |  08:30:16.2  |
|  Event   43  |  08:30:26.4  |  00:00:03.7  |  08:30:30.1  |
|  Event   44  |  08:30:40.0  |  00:00:04.4  |  08:30:44.4  |
|  Event   45  |  08:31:41.0  |  00:00:07.3  |  08:31:48.3  |
|  Event   46  |  08:32:22.1  |  00:00:03.8  |  08:32:26.0  |
|  Event   47  |  08:33:45.9  |  00:00:04.4  |  08:33:50.3  |
|  Event   48  |  08:34:32.0  |  00:00:04.6  |  08:34:36.6  |
|  Event   49  |  08:35:19.4  |  00:00:10.4  |  08:35:29.8  |
|  Event   50  |  08:35:31.5  |  00:00:08.2  |  08:35:39.6  |
|  Event   51  |  08:41:35.2  |  00:00:15.6  |  08:41:50.8  |
|  Event   52  |  08:41:56.1  |  00:00:29.9  |  08:42:26.0  |
|  Event   53  |  08:42:35.3  |  00:00:19.3  |  08:42:54.5  |
|  Event   54  |  08:43:08.5  |  00:00:05.3  |  08:43:13.8  |
|  Event   55  |  08:43:35.3  |  00:00:10.1  |  08:43:45.4  |
|  Event   56  |  08:43:53.5  |  00:00:05.0  |  08:43:58.5  |
|  Event   57  |  08:44:00.0  |  00:00:09.1  |  08:44:09.0  |
|  Event   58  |  08:44:24.2  |  00:00:05.4  |  08:44:29.6  |
|  Event   59  |  08:44:29.6  |  00:00:09.7  |  08:44:39.3  |
|  Event   60  |  08:44:39.3  |  00:00:03.0  |  08:44:42.3  |
|  Event   61  |  08:44:57.4  |  00:00:04.2  |  08:45:01.7  |
|  Event   62  |  09:06:20.2  |  00:00:11.0  |  09:06:31.2  |
|  Event   63  |  09:06:45.7  |  00:00:11.5  |  09:06:57.2  |
|  Event   64  |  09:06:58.0  |  00:00:03.7  |  09:07:01.7  |
|  Event   65  |  09:19:30.0  |  00:00:05.0  |  09:19:35.0  |
|  Event   66  |  09:19:37.0  |  00:00:11.1  |  09:19:48.1  |
|  Event   67  |  09:21:09.4  |  00:00:22.8  |  09:21:32.2  |
|  Event   68  |  09:24:02.8  |  00:00:11.8  |  09:24:14.6  |
|  Event   69  |  09:25:26.8  |  00:00:04.1  |  09:25:30.9  |
|  Event   70  |  09:25:47.5  |  00:00:04.2  |  09:25:51.7  |
|  Event   71  |  09:25:51.7  |  00:00:02.7  |  09:25:54.4  |
|  Event   72  |  09:27:05.9  |  00:00:22.2  |  09:27:28.1  |
|  Event   73  |  09:27:28.2  |  00:00:05.9  |  09:27:34.0  |
|  Event   74  |  09:27:44.9  |  00:00:04.2  |  09:27:49.1  |
|  Event   75  |  09:28:06.3  |  00:00:14.2  |  09:28:20.5  |
|  Event   76  |  09:28:21.8  |  00:00:32.4  |  09:28:54.2  |
|  Event   77  |  09:28:56.6  |  00:00:40.0  |  09:29:36.7  |
|  Event   78  |  09:29:53.0  |  00:00:03.7  |  09:29:56.7  |
|  Event   79  |  09:30:13.4  |  00:00:10.9  |  09:30:24.4  |
|  Event   80  |  09:32:31.2  |  00:00:09.6  |  09:32:40.8  |
|  Event   81  |  09:32:43.8  |  00:00:06.0  |  09:32:49.8  |
|  Event   82  |  09:32:54.6  |  00:00:04.2  |  09:32:58.7  |
|  Event   83  |  09:34:00.7  |  00:00:14.5  |  09:34:15.2  |
|  Event   84  |  09:34:15.5  |  00:00:24.6  |  09:34:40.1  |
|  Event   85  |  09:34:40.1  |  00:00:12.0  |  09:34:52.1  |
|  Event   86  |  09:35:13.4  |  00:00:10.4  |  09:35:23.9  |
|  Event   87  |  09:35:36.8  |  00:00:06.8  |  09:35:43.6  |
|  Event   88  |  09:35:43.6  |  00:00:10.7  |  09:35:54.3  |
|  Event   89  |  09:35:59.9  |  00:00:10.9  |  09:36:10.8  |
|  Event   90  |  09:36:12.2  |  00:00:05.6  |  09:36:17.8  |
|  Event   91  |  09:36:18.4  |  00:00:12.9  |  09:36:31.3  |
|  Event   92  |  09:36:32.2  |  00:00:23.5  |  09:36:55.7  |
|  Event   93  |  09:38:20.6  |  00:00:06.7  |  09:38:27.4  |
|  Event   94  |  09:38:30.6  |  00:00:09.2  |  09:38:39.8  |
|  Event   95  |  09:38:59.3  |  00:00:05.3  |  09:39:04.6  |
|  Event   96  |  09:39:11.0  |  00:00:05.4  |  09:39:16.4  |
|  Event   97  |  09:39:21.8  |  00:00:05.3  |  09:39:27.1  |
|  Event   98  |  09:39:46.8  |  00:00:05.3  |  09:39:52.0  |
|  Event   99  |  09:40:00.1  |  00:00:26.0  |  09:40:26.1  |
|  Event  100  |  09:40:26.5  |  00:00:33.0  |  09:40:59.6  |
|  Event  101  |  09:41:09.8  |  00:00:04.3  |  09:41:14.1  |
|  Event  102  |  09:41:14.4  |  00:00:39.7  |  09:41:54.1  |
|  Event  103  |  09:42:51.0  |  00:00:04.9  |  09:42:55.9  |
|  Event  104  |  09:43:31.1  |  00:00:04.7  |  09:43:35.8  |
|  Event  105  |  09:43:39.4  |  00:00:05.2  |  09:43:44.6  |
|  Event  106  |  09:43:50.0  |  00:00:18.6  |  09:44:08.6  |
|  Event  107  |  09:44:27.2  |  00:00:10.4  |  09:44:37.6  |
|  Event  108  |  09:45:13.5  |  00:00:11.2  |  09:45:24.7  |
|  Event  109  |  09:45:25.8  |  00:00:09.4  |  09:45:35.2  |
|  Event  110  |  09:45:36.7  |  00:00:04.7  |  09:45:41.4  |
|  Event  111  |  09:45:52.5  |  00:00:15.8  |  09:46:08.3  |
|  Event  112  |  09:46:08.3  |  00:00:10.6  |  09:46:19.0  |
|  Event  113  |  09:46:19.0  |  00:00:03.4  |  09:46:22.4  |
|  Event  114  |  09:46:25.2  |  00:00:21.8  |  09:46:47.0  |
|  Event  115  |  09:46:50.2  |  00:00:29.9  |  09:47:20.1  |
|  Event  116  |  09:47:20.6  |  00:00:20.0  |  09:47:40.7  |
|  Event  117  |  09:47:40.7  |  00:00:57.1  |  09:48:37.8  |
|  Event  118  |  09:48:47.3  |  00:00:04.4  |  09:48:51.7  |
|  Event  119  |  09:48:51.7  |  00:00:04.0  |  09:48:55.7  |
|  Event  120  |  09:48:55.7  |  00:00:04.2  |  09:48:59.9  |
|  Event  121  |  09:49:02.1  |  00:00:15.2  |  09:49:17.3  |
|  Event  122  |  09:49:19.6  |  00:00:04.7  |  09:49:24.3  |
|  Event  123  |  09:49:24.3  |  00:00:08.8  |  09:49:33.1  |
|  Event  124  |  09:49:34.7  |  00:00:08.9  |  09:49:43.6  |
|  Event  125  |  09:49:45.4  |  00:00:04.2  |  09:49:49.6  |
|  Event  126  |  09:50:09.2  |  00:00:04.4  |  09:50:13.6  |
|  Event  127  |  09:50:24.2  |  00:00:04.0  |  09:50:28.2  |
|  Event  128  |  09:52:16.6  |  00:00:15.7  |  09:52:32.3  |
|  Event  129  |  09:52:43.9  |  00:00:04.4  |  09:52:48.3  |
-------------------------------------------------------------

The command for this process was as follows:

dvr-scan -i "C:\Directory\video.mkv" -o "C:\Directory\video.avi" -b mog2_cuda -tc

**Expected Behavior:**
The video will finish being scanned and output an AVI video in the directory with the identified events and their timecodes.

**Computing Environment:**
Windows 11 Pro, RTX 4090 Notebook, DVR-scan 1.5.1, NVIDIA CUDA Windows Build (64-bit )

**Additional Information:**
This is maybe my 10th or 11th time using DVR-Scan with no problems up until this point.

**Comment by Breakthrough** [comment]
I think this error might be coming from ffmpeg when trying to decode the video.  You may want to re-encode the video with `ffmpeg` or see if passing it through `mkvmerge` fixes the issue.
