### ISSUE TITLE
cnt mode stuck 

### ISSUE THREAD

**Issue by dassio** [Breakthrough/DVR-Scan#144]
**Bug/Issue Description:**
When using CNT mode, the process is stuck

**Required Information:**

![dvr-scan](https://github.com/Breakthrough/DVR-Scan/assets/733502/bc1dc008-f24b-477c-9a8f-5a39d6009057)

**Computing Environment:**
 - OS: Ubuntu
 - Python Version:  3.9
 - OpenCV Version:  opencv-python          4.5.3.56

**Comment by Breakthrough** [comment]
Could you provide some debug logs (`--verbosity debug`) and also let me know what the output is when using MOG?  Does the issue happen if you re-encode the input video first?

**Comment by Breakthrough** [comment]
Is it possible for you to share the video?  The detector you use shouldn't affect how the video is decoded. It looks like in the screenshot the video has some issues with it.

Can you elaborate more on what you mean by stuck?

**Comment by dassio** [comment]
I just happened to reinstall the OS (before I had python2 installed), and now it seems that everything is working
