### ISSUE TITLE
Unsupported config option: region-file

### ISSUE THREAD

**Issue by lublak** [Breakthrough/DVR-Scan#153]
**Bug/Issue Description:**

Currently i try to use the option region-file in the config. I get an error:
```
Unsupported config option: region-file
```

**Required Information:**

```
dvr-scan.exe --input 10.243.7.181_14.mxg --config dvr-scan.cfg
```

**Computing Environment:**
 - OS: Windows 10
 - Python Version: I downloaded the portable exe
 - OpenCV Version: I downloaded the portable exe

**Comment by Breakthrough** [comment]
Similar to #154 there is no way to specify a region file path with a config file.  However I can consider adding it in a future version.

**Comment by felixscheffer** [comment]
I use `load-region = region.txt` in the config file and it works just fine:

```
[DVR-Scan] Loading regions from file: region.txt
[DVR-Scan] Limiting detection to 1 region.
```

**Comment by Breakthrough** [comment]
Sorry I realize now this was a mistake in the documentation, indeed the config option is called `load-region`.  I'll push a fix for the docs soon, thanks!
