### ISSUE TITLE
region-editor config option gets ignored

### ISSUE THREAD

**Issue by lublak** [Breakthrough/DVR-Scan#154]
**Bug/Issue Description:**

Currently i try to use the option region-editor in the config to always open the region editor before scanning the video.

**Required Information:**

```
dvr-scan.exe --input 10.243.7.181_14.mxg --config dvr-scan.cfg
```

**Expected Behavior:**

It should open the Editor and after selecting the region it should run the scan.

**Computing Environment:**
 - OS: Windows 10
 - Python Version: I downloaded the portable exe
 - OpenCV Version: I downloaded the portable exe

**Comment by Breakthrough** [comment]
Currently you must specify the `-r`/`--region-editor` flag explicitly, there is no way to automatically launch it.

I will consider adding a config option to allow setting if it should always be launched in the next version.

**Comment by lublak** [comment]
O i though because there is an option in the default config:
https://github.com/Breakthrough/DVR-Scan/blob/main/dvr-scan.cfg#L25
https://github.com/Breakthrough/DVR-Scan/blob/main/dvr-scan.cfg#L96

**Comment by Breakthrough** [comment]
Good catch, will definitely fix this in the next release.  Thanks for the report.

**Comment by felixscheffer** [comment]
I use `load-region = region.txt` in the config file and it works just fine:

```
[DVR-Scan] Loading regions from file: region.txt
[DVR-Scan] Limiting detection to 1 region.
```
