### ISSUE TITLE
Scan Zone / Region

### ISSUE THREAD

**Issue by petetheman79** [Breakthrough/DVR-Scan#18]
Is there a way to scan a specific zone in the video, so that one can focus on specific areas of interest in order to reduce the number of matches such a trees blowing in the wind.

**Comment by ninguemrj** [comment]
I would like a feature like this too

**Comment by Breakthrough** [comment]
This was actually implemented in #3; if you download and install the latest version of the DVR-Scan source code here from Github ( https://github.com/Breakthrough/DVR-Scan/archive/master.zip ), you can supply a `-roi` argument.  See [this comment](https://github.com/Breakthrough/DVR-Scan/issues/3#issuecomment-507718860) for usage details.

**Comment by unformatt** [comment]
Could this version be released and docs updated?

**Comment by SKempin** [comment]
Agreed, could this be released and updated @Breakthrough ?

**Comment by Breakthrough** [comment]
This is now available in the latest release of DVR-Scan (the `-roi` argument).
