### ISSUE TITLE
-q/--quiet mode does not work correctly

### ISSUE THREAD

**Issue by mxdog** [Breakthrough/DVR-Scan#19]
dvr-scan  -i "F:\Media\Videos\12-04-06;06.mp4" --quiet -st 00:00:00.005 -l 15 -tb 1 -tp 0.001s -t .40 -so

does not produce the expected outcome. I was expecting only the list of events but the full output is produced. 

**Was expecting only this !** 

00:00:29.200,00:00:31.300,00:00:42.300,00:00:42.700,00:00:54.000,00:00:54.300,00:01:20.500,00:01:20.800,00:01:35.000,00:01:35.300,00:01:51.200,00:01:51.400,00:02:03.700,00:02:06.600,00:02:12.600,00:02:13.100,00:02:19.400,00:02:20.100,00:02:26.500,00:02:27.500,00:02:33.800,00:02:35.900,00:02:55.200,00:02:55.600,00:03:35.000,00:03:36.200,00:03:55.100,00:03:55.600,00:04:15.300,00:04:15.800,00:04:42.500,00:04:43.400,00:04:49.800,00:04:50.200,00:04:57.000,00:04:57.900,00:05:04.100,00:05:10.300

**NOT** 

[DVR-Scan] Scanning input video for motion events...
[DVR-Scan] Processed 3122 / 3122 frames read in 2.4 secs (avg 1303.6 FPS).
[DVR-Scan] Detected 19 motion events in input.
[DVR-Scan] Scan-only mode specified, list of motion events:
-------------------------------------------------------------
|   Event #    |  Start Time  |   Duration   |   End Time   |
-------------------------------------------------------------
|  Event    1  |  00:00:29.2  |  00:00:02.1  |  00:00:31.3  |
|  Event    2  |  00:00:42.3  |  00:00:00.4  |  00:00:42.7  |
|  Event    3  |  00:00:54.0  |  00:00:00.3  |  00:00:54.3  |
|  Event    4  |  00:01:20.5  |  00:00:00.3  |  00:01:20.8  |
|  Event    5  |  00:01:35.0  |  00:00:00.3  |  00:01:35.3  |
|  Event    6  |  00:01:51.2  |  00:00:00.2  |  00:01:51.4  |
|  Event    7  |  00:02:03.7  |  00:00:02.9  |  00:02:06.6  |
|  Event    8  |  00:02:12.6  |  00:00:00.5  |  00:02:13.1  |
|  Event    9  |  00:02:19.4  |  00:00:00.7  |  00:02:20.1  |
|  Event   10  |  00:02:26.5  |  00:00:01.0  |  00:02:27.5  |
|  Event   11  |  00:02:33.8  |  00:00:02.1  |  00:02:35.9  |
|  Event   12  |  00:02:55.2  |  00:00:00.4  |  00:02:55.6  |
|  Event   13  |  00:03:35.0  |  00:00:01.2  |  00:03:36.2  |
|  Event   14  |  00:03:55.1  |  00:00:00.5  |  00:03:55.6  |
|  Event   15  |  00:04:15.3  |  00:00:00.5  |  00:04:15.8  |
|  Event   16  |  00:04:42.5  |  00:00:00.9  |  00:04:43.4  |
|  Event   17  |  00:04:49.8  |  00:00:00.4  |  00:04:50.2  |
|  Event   18  |  00:04:57.0  |  00:00:00.9  |  00:04:57.9  |
|  Event   19  |  00:05:04.1  |  00:00:06.2  |  00:05:10.3  |
-------------------------------------------------------------
[DVR-Scan] Comma-separated timecode values:
00:00:29.200,00:00:31.300,00:00:42.300,00:00:42.700,00:00:54.000,00:00:54.300,00:01:20.500,00:01:20.800,00:01:35.000,00:01:35.300,00:01:51.200,00:01:51.400,00:02:03.700,00:02:06.600,00:02:12.600,00:02:13.100,00:02:19.400,00:02:20.100,00:02:26.500,00:02:27.500,00:02:33.800,00:02:35.900,00:02:55.200,00:02:55.600,00:03:35.000,00:03:36.200,00:03:55.100,00:03:55.600,00:04:15.300,00:04:15.800,00:04:42.500,00:04:43.400,00:04:49.800,00:04:50.200,00:04:57.000,00:04:57.900,00:05:04.100,00:05:10.300

**Comment by mic704b** [comment]
It doesn't work on Linux either

DVR-scan v1.0.1

**Comment by Breakthrough** [comment]
This definitely affects the current release, my apologies.  This was due to me using print statements instead of a proper logger.  Will investigate how I can cleanly fix this without making any major API changes.  Thanks for letting me know!

**Comment by Breakthrough** [comment]
Fixed in v1.2 branch, will be included in next release of DVR-Scan.  Thanks for the report!
