### ISSUE TITLE
AttributeError: 'module' object has no attribute 'VideoWriter_fourcc', and add OpenCV to setup.py

### ISSUE THREAD

**Issue by dedulat** [Breakthrough/DVR-Scan#2]
I tried using dvr-scan and received the following error:

$ dvr-scan -i 20170806124722.avi 
[DVR-Scan] Initializing scan context...
Traceback (most recent call last):
  File "/usr/local/bin/dvr-scan", line 9, in <module>
    load_entry_point('DVR-Scan==1.0.1', 'console_scripts', 'dvr-scan')()
  File "build/bdist.linux-x86_64/egg/dvr_scan/__init__.py", line 63, in main
  File "build/bdist.linux-x86_64/egg/dvr_scan/scanner.py", line 80, in __init__
AttributeError: 'module' object has no attribute 'VideoWriter_fourcc'

From what I could tell it seemed to be related to the version of Python.  I tried changing /usr/local/bin/dvr-scan from /usr/bin/python to /usr/bin/python3 and received the following error:

$ dvr-scan -i 20170806124722.avi 
[DVR-Scan] Initializing scan context...
Traceback (most recent call last):
  File "/usr/local/bin/dvr-scan", line 9, in <module>
    load_entry_point('DVR-Scan==1.0.1', 'console_scripts', 'dvr-scan')()
  File "build/bdist.linux-x86_64/egg/dvr_scan/__init__.py", line 63, in main
  File "build/bdist.linux-x86_64/egg/dvr_scan/scanner.py", line 80, in __init__
AttributeError: 'module' object has no attribute 'VideoWriter_fourcc'

**Comment by Breakthrough** [comment]
Hello @dedulat;

Thanks for the report, will look into this.  However, given the error in particular, I'm not sure it has to do with the particular version of Python (I will double-check this, however), but perhaps the OpenCV module (the Python `cv2`) module that is being used.

Did you manually install the OpenCV Python libraries?  If so, I can give you a small Python script which can test that everything was installed correctly.  Also, just to know, what OS are you using?  (I assume Linux?)

**Comment by leathamie** [comment]
Hello, 
I have the same issue could you explain me how you resolved it last time ? 
(I did manually install the OpenCV Python librairies, and I'm using Ubuntu 16.04)

Thanx! :)

**Comment by roccodm** [comment]
I had the some issue, but i solved in debian stretch in this way:
sudo apt-get remove python-opencv
sudo pip install opencv-python

**Comment by Breakthrough** [comment]
I wonder if this has to do with me misdetecting the version of OpenCV that you're using, or the fact that only recently has the `opencv-python` package on pip started shipping with binaries on all platforms.

I may update the setup.py file to add that as an optional dependency, as I did with PySceneDetect.

**Comment by RikJohnsonUK** [comment]
Same problem here :-( Fix didn't work for me

dvr-scan -i /home/sysops/Videos/test.avi
[DVR-Scan] Initializing scan context...
Traceback (most recent call last):
File "/usr/local/bin/dvr-scan", line 9, in
load_entry_point('DVR-Scan==1.0.1', 'console_scripts', 'dvr-scan')()
File "build/bdist.linux-x86_64/egg/dvr_scan/init.py", line 63, in main
File "build/bdist.linux-x86_64/egg/dvr_scan/scanner.py", line 78, in init
AttributeError: 'module' object has no attribute 'VideoWriter_fourcc'

**Comment by Breakthrough** [comment]
Resolved by #30 (specifically 862e2cce3415a11fa7bc6fde9f7d720e4a976135).
