### ISSUE TITLE
Detect blobs

### ISSUE THREAD

**Issue by lbdc** [Breakthrough/DVR-Scan#21]
Just wondering if there is a way for DVR-Scan to detect "blobs of pixel" or "continuous areas" to prevent false detection due to rain, snow and noise.

If not could this be implemented as enhancement?

**Comment by Breakthrough** [comment]
It's definitely technically possible, one could supply an image as a mask (e.g. a transparent .png).  Not sure when I'll be able to get to this, but I'm more than open to implementing it for sure, great idea.

**Comment by Breakthrough** [comment]
Hopefully with adjusting kernel size and the new region editor, it should be easier to mask out certain areas and small blobs.
