### ISSUE TITLE
setuptools is a dependency

### ISSUE THREAD

**Issue by stevegilbert23** [Breakthrough/DVR-Scan#22]
Please add "setuptools" to the list under "Installing Dependencies": https://dvr-scan.readthedocs.io/en/latest/guide/installing/

install.py fails if setuptools is not installed.

**Comment by Breakthrough** [comment]
Note that now this package is available on `pip`, which reduces the number of people that need to install a source distribution.  I agree though that the documentation should make that more clear.

**Comment by Breakthrough** [comment]
Can you share how you were installing when you ran this?  Did you install the requirements file via `pip` first?  (e.g. `pip install -r requirements.txt`)?

Will be addressing this in the next release of DVR-Scan for sure.

**Comment by Breakthrough** [comment]
Requirements are now pinned correctly - this shouldn't be affecting anyone anymore, but if it does crop up, please let me know or raise another issue.  Thank you!
