### ISSUE TITLE
"non-existing PPS 0 referenced"

### ISSUE THREAD

**Issue by wakeupwakeup** [Breakthrough/DVR-Scan#24]
I'm getting with all my avi videos this messages , in generates de avi with the movements but perhaps not all?
Thanks

[h264 @ 07516040] non-existing PPS 0 referenced
[h264 @ 07516040] decode_slice_header error
[h264 @ 07516040] no frame!

**Comment by Breakthrough** [comment]
Unfortunately this is not a DVR-Scan issue, but deals with how `ffmpeg` decodes video streams.  This is what happens before ffmpeg has enough data to decode the first I-frame, if I recall correctly.

Does decoding fail entirely?  Or is the rest of the file processed?

**Comment by wakeupwakeup** [comment]
It continues working in the file, and I gives again the same error several times... but I wonder if it is losing some movement detection when that fails.
Thanks

**Comment by Breakthrough** [comment]
Hi @wakeupwakeup;

Could you share some more details with me to resolve this issue?  In particular, what version of ffmpeg are you using?  What OS/version?  Can you share one of the files that has this error in it?

Thank you!

**Comment by Breakthrough** [comment]
Closing due to lack of response / required information for further triaging.  Please feel free to comment still on this issue, or create a new one, should you be able to provide it.  Thank you.
