### ISSUE TITLE
Failed to load OpenH264 library

### ISSUE THREAD

**Issue by radpopl** [Breakthrough/DVR-Scan#25]
I downloaded openh264-1.6.0-win64msvc.dll and put in DVR-Scan folder.

But I still get:

Failed to load OpenH264 library: openh264-1.4.0-win64msvc.dll
        Please check environment and/or download library from here: https://gith
ub.com/cisco/openh264/releases

[libopenh264 @ 0000000003d63b00] Incorrect library version loaded
Could not open codec 'libopenh264': Unspecified error
[libopenh264 @ 00000000051a77c0] Incorrect library version loaded
Could not open codec 'libopenh264': Unspecified error
[libopenh264 @ 0000000002270760] Incorrect library version loaded
Could not open codec 'libopenh264': Unspecified error
[libopenh264 @ 00000000043fe420] Incorrect library version loaded
Could not open codec 'libopenh264': Unspecified error

**Comment by Breakthrough** [comment]
Hi @radpopl;

It looks like the incorrect version is being loaded.  The error you're seeing specifies you should use v1.4.0, but your comment implies you downloaded v1.6.0.

Can you try with v1.4.0 and see if it resolves the issue?  Thanks!

**Comment by Breakthrough** [comment]
Closing until response received.
