### ISSUE TITLE
Wont scan - bails with AttributeError: 'module' object has no attribute 'VideoWriter_fourcc'

### ISSUE THREAD

**Issue by RikJohnsonUK** [Breakthrough/DVR-Scan#26]
As per title - any attempt to scan a video file results in:

AttributeError: 'module' object has no attribute 'VideoWriter_fourcc'

Tried on known good mp4 & avi files from different CCTV devices.

OS: Ubuntu 16.04.6 LTS
Python 2.7.12

DUMP
dvr-scan -i  /home/sysops/Videos/test.avi 
[DVR-Scan] Initializing scan context...
Traceback (most recent call last):
  File "/usr/local/bin/dvr-scan", line 9, in <module>
    load_entry_point('DVR-Scan==1.0.1', 'console_scripts', 'dvr-scan')()
  File "build/bdist.linux-x86_64/egg/dvr_scan/__init__.py", line 63, in main
  File "build/bdist.linux-x86_64/egg/dvr_scan/scanner.py", line 78, in __init__
AttributeError: 'module' object has no attribute 'VideoWriter_fourcc'

Tried a fix shown in thread:

sudo apt-get remove python-opencv
sudo pip install opencv-python

No dice.

any help/pointers?

**Comment by Breakthrough** [comment]
Hello @ RikJohnsonUK;

It seems like this was something missed in the OpenCV compatibility layer.  I've pushed a fix for this to master.  Can you follow up and let me know if it resolves the issue?

You can download a new copy of the DVR-Scan source code [from here](https://github.com/Breakthrough/DVR-Scan/archive/master.zip).

Alternatively, if you update to OpenCV 3.0+, it should also resolve the issue, however my intention is for DVR-Scan to work on 2.x as well, so if you can test + verify the fix I've pushed to the repo, that would be much appreciated.

Thank you for the report!

**Comment by RikJohnsonUK** [comment]
Hi,

Thanks for doing this Brandon.

DVR-SCAN now appears to read and open videos, but now bombs out with this:

Traceback (most recent call last):
   File "/usr/local/bin/dvr-scan", line 9, in <module>
     load_entry_point('DVR-Scan==1.0.1', 'console_scripts', 'dvr-scan')()
   File "build/bdist.linux-x86_64/egg/dvr_scan/__init__.py", line 66, in 
main
   File "build/bdist.linux-x86_64/egg/dvr_scan/scanner.py", line 230, in 
scan_motion
AttributeError: 'module' object has no attribute 
'createBackgroundSubtractorMOG2'

**Comment by Breakthrough** [comment]
Hi @RikJohnsonUK;

What happens if you install `pip install opencv-contrib-python` instead?

Thanks!

**Comment by RikJohnsonUK** [comment]
It may break other stuff. I dumped this and went with a commercial 
solution on my Mac instead. Thanks anyway.

**Comment by Breakthrough** [comment]
Gotcha, thanks for the follow up.  Will do some testing on my own end and try to find a resolution before closing this.
