### ISSUE TITLE
Idea: Add rectangular region of detection

### ISSUE THREAD

**Issue by ManOfFlash** [Breakthrough/DVR-Scan#3]
For detecting movement only on specified region of video frame.

**Comment by Breakthrough** [comment]
Great idea, thank you @ManOfFlash for the suggestion.  I will definitely look into adding this; also need to figure out what CLI arguments should be provided.

**Comment by ManOfFlash** [comment]
It's how i imaging using this feature.
Provide 4 numbers for rectangle coordinates.
`dvr-scan .... -rect 60,120,204,350`
where 60,120 x and y of top left coordinates(in pixels) of corner of Interested region.

**Comment by mianor64** [comment]
I need this as well !

**Comment by ibravo** [comment]
Check the work from a similar project in Github that implemented this rectangle option. Might serve as an inspiration:
https://github.com/jooray/motion-detection

**Comment by mattncsu** [comment]
I'd love to see this too!

**Comment by molly78** [comment]
I third or fourth this!

I can't believe there is no software I've found that can do this...

**Comment by molly78** [comment]
> As a workaround, I cropped the video in handbrake and then ran the cropped video through DVR-Scan which works ok if your area of interest is rectangular.

Interesting idea, but I’m looking to process a month worth of camera footage at a time...

Yay for many cores....

**Comment by klucsik** [comment]
I added a pull request with the solution. I used the selectROI function to make the rectangle in a pop-up window, the the code slices each frame before motion detection to the selected rectangle. After motion detection, the original frames selected for writing. 
I currently trying to make a CLI interface for the rectangle creation so you don't need to mess with the pop-up window if it is not needed

**Comment by mattncsu** [comment]
Thanks!

**Comment by klucsik** [comment]
[(https://github.com/Breakthrough/DVR-Scan/pull/13/commits/abd5f59c325fdae5dd0e935ba3ab8c906ac8890c)]
Here is the update with the CLI interface. I hope the help what i wrote explains it clearly.

**Comment by klucsik** [comment]
[(https://github.com/Breakthrough/DVR-Scan/pull/13/commits/abd5f59c325fdae5dd0e935ba3ab8c906ac8890c)](url)
Here is the update with the CLI interface! I hope the help what I wrote explains it clearly.

**Comment by Breakthrough** [comment]
Merged #13 just now which addresses this issue - thanks @klucsik for your work on this!

There is now a `-roi` command-line option which can be used to select a rectangular area of detection.  You can specify the coordinates in x,y,w,h, or don't specify any coordinates and a pop-up window will appear allowing you to select the rectangle with your mouse ontop of the first frame in the video.

This will be available in the next (and possibly final) release of DVR-Scan, before it gets merged with PySceneDetect.  To use this feature immediately, you can [download and install the latest version of DVR-Scan](https://github.com/Breakthrough/DVR-Scan/archive/master.zip) from the master branch on Github.

**Comment by Breakthrough** [comment]
Will be included officially as part of v1.1 release today!  Thank you all again!
