### ISSUE TITLE
Non rectangular region of interest

### ISSUE THREAD

**Issue by matsalleh92** [Breakthrough/DVR-Scan#39]
Would there be a way to have a non rectangular (polygon) region  of interest like in ZoneAlarm?

In my specific case there are trees that blow in the wind that trigger detection, but the position of the camera does not allow easy removal from the ROI using a rectangle.

**Comment by Breakthrough** [comment]
I think the best way to approach this would be to allow specifying an image as a mask - either multiplying it with the image in RGB.  That way you can make a mask by saving a frame from the video and painting the parts you want included in white and excluded in black.

We should also allow an alpha channel to be specified in which case that would be used as the mask itself.

**Comment by Breakthrough** [comment]
I've made some progress on this and this should be included when DVR-Scan v1.6 is completed. Here's a sample of what's to come:

![image](https://github.com/Breakthrough/DVR-Scan/assets/125316/cd1b3481-6e92-499e-8655-f0d3be9b5673)

You can use the mouse to drag existing points or add new ones, to define arbitrary shapes.  I don't know if the GUI will support multiple shapes for the first iteration, but it might in the future.  However, on command line and via config file, you will be able to specify multiple non-rectangular ROIs that may or may not overlap.

This isn't functional yet, but should be soon - I'll post an update when something is available for folks to test out.  Thanks!

**Comment by Breakthrough** [comment]
Fix will be included in v1.6 release, thanks!

**Comment by Breakthrough** [comment]
v1.6 is now out, feedback on the new feature is most welcome!
