### ISSUE TITLE
Motion file has bigger size than original

### ISSUE THREAD

**Issue by ibravo** [Breakthrough/DVR-Scan#42]
My source file for an IP camera footage is a H264 - MPEG-4 AVC (part 10) (h264) and when converting with dvr-scan -c H264 to produce a motion based output, this output is 3x bigger in those situations where there is plenty of movement in the footage. I can't fully understand why this is the case.

- Is there a way to do a simple stripping of the file without re-encoding the file?
- When we add X seconds at the beginning and end of each clip, if these buffers coincide (the end of one with the beginning of the other), are they duplicated?

**Comment by Breakthrough** [comment]
Hey @ibravo;

This is definitely possible - the current architecture was designed around purely an OpenCV-based design.  However, I'm open to expanding that to include ffmpeg/mkvmerge as I did with PySceneDetect (I might be able to re-use that functionality here by actually building DVR-Scan ontop of the existing `scenedetect` API).

Will definitely look into tackling this, thank you for the suggestion!

As for your last question, the current implementation will still produce two distinct events and not combine them if the regions overlap.  This is something I could consider if required, but would need come up with a good way of integrating it with the existing design (or changing it to support merging).

**Comment by ibravo** [comment]
As a workaround I was thinking in using 'dvr-scan -so' to provide the timestamps of the different clips using the -scan only option, and then passing it up to ffmpeg to do the slicing of the video with the 'ffmpeg -ss [start] -to[end] -i in.mp4 -c copy out.mp4'
This would create multiple files, instead of the preferred just one.

I was about to research this as an alternative, but I don't know if it would work.

**Comment by Breakthrough** [comment]
That's definitely a good approach @ibravo - that's it's actually done in PySceneDetect as well!  This would also resolve the lack of audio (#27) in the output.  After splitting into individual files, you can also use `ffmpeg` to concatenate them again without re-encoding either.

I'm hoping to resolve this in the next release of DVR-Scan, which will bring greater integration with PySceneDetect (since it already provides an API to accomplish this).  In the meantime, let me know if you have any questions regarding the approach with `ffmpeg`, as that should provide a workaround for the time being.

Thanks!

**Comment by angelferre** [comment]
Hi @Breakthrough 

I have been testing with a 5 min test video by myself ("Test_5min.mkv"). As @ibravo suggested, I have performed a DVR-Scan with the -so options, exporting event timecodes to "events.txt", and I have used the timestamps to split the original file in multiple event files with ffmpeg, then concatenated with ffmpeg without re-encoding. Doing so, theoretically, we could obtain an output file with the same fps, bitrate, etc. than the original, but with motion detection.

I am first launching DVR-Scan and exporting events to a file:

dvr-scan -tb 0.5s -tp 0.5s -t 0.5 -l 4 -i /media/ftp/angel/Test/Test_5min.mkv -so | tail -1 > events.txt

[events.txt](https://github.com/Breakthrough/DVR-Scan/files/6272733/events.txt)

These are the events stored in "events.txt" generated by DVR-Scan (start,end):

00:00:01.625,00:00:09.375,
00:00:36.375,00:00:39.875,
00:01:05.750,00:01:12.875,
00:01:15.875,00:01:19.000,
00:01:37.500,00:01:42.875,
00:02:39.000,00:02:42.250,
00:02:58.125,00:02:59.750,
00:03:21.000,00:03:22.750,
00:03:47.000,00:03:54.625,
00:04:12.750,00:04:16.000,
00:04:32.750,00:04:37.875,
00:05:09.875,00:05:11.250

(Note that last event from 00:05:09.875 to 00:05:11.250 is not even possible, as the video has a duration of 00:05:00. All the rest of events seem to me shifted, they don't match while checking the video manually)

To fix that I converted input video to mp4 with ffmpeg:

ffmpeg -i Test_5min.mkv Test_5min.mp4

New time events are:

00:00:00.375,00:00:01.000,
00:00:01.625,00:00:09.125,
00:00:31.000,00:00:31.500,
00:00:35.125,00:00:38.500,
00:01:03.375,00:01:16.000,
00:01:34.000,00:01:39.000,
00:02:32.875,00:02:36.000,
00:02:51.250,00:02:52.750,
00:03:13.125,00:03:14.875,
00:03:38.125,00:03:49.500,
00:04:03.000,00:04:10.125,
00:04:22.000,00:04:31.000,
00:04:57.750,00:04:59.000

These are correct according to the video!

After that I create event files and concatenate them for the output file with a bash script:
[concat_video.zip](https://github.com/Breakthrough/DVR-Scan/files/6272757/concat_video.zip)

So DVR-Scan generates correct timestamps when input video is in mp4, but slightly shifted ones when in mkv format of same duration. Do you know the reason for that?

Thanks in advance

**Comment by Breakthrough** [comment]
Hi @angelferre;

That is strange indeed.  Can you try using the following to convert it and show the result:

    ffmpeg -i video.mkv -c:v copy -c:a copy video.mp4

Could you provide the output when converting it to MP4, as well as seeing if adding `-c:v copy -c:a copy` changes anything?

Lastly, are you able to share the mkv here by any chance?  (If not, no worries)

**Comment by dassio** [comment]
here is the bash i used:


```
#!/bin/bash

events_time_stamp="events.txt"
split_video () {
    local video_file=$1
        local start=0
    local end=0
    local events_array
    IFS=',' read -ra events_array <<< `cat events.txt`
    
        for event in "${events_array[@]}"; do
        index=$((index+1))
        if [ $(($index%2)) -eq 1 ]
            then
                start=$event
        fi
        if [ $(($index%2)) -eq 0 ]
            then
                end=$event
                        ffmpeg -y -i $video_file -ss $start -to $end  -c copy "${video_file%.mp4}_split_$(($index/2)).mp4"
        fi
    done
        for f in ./*split*.mp4; do echo " file '$PWD/$f'"; done  >> split_files
        ffmpeg -y -f concat -safe 0 -i split_files -c copy "${video_file%.mp4}_detect_motion.mp4"
        rm split_fiiles
        rm events.txt
        rm *split*.mp4
}

detect_motion () {
        local video_file=$1
        dvr-scan -i $video_file -so | tail -1 > $events_time_stamp
}
detect_motion $1
split_video $1```

**Comment by kiska3** [comment]
Hey there I am assuming OpenCV is still being used for video as I have a 1.7GB 1 hour file, with about 20 minutes of motion somehow being 3GB much bigger than the original.

**Comment by Breakthrough** [comment]
In the long term, will need to add a special argument to allow this.  As workarounds exists though, will push that to a future release.

Note that this would not work with timecodes/bounding boxes either.

**Comment by angelferre** [comment]
Thanks for the information!

This features will be very helpful for our applications, we keep waiting for v1.5 to be issued, any forecast?

BR

 



 



 

Angel Ferre Giménez

General Manager

M:      +34 627 48 25 20 

E:        ***@***.***> ***@***.*** 

@Sant Cugat Business Park

Av. Via Augusta, 15-25

08174 Sant Cugat del Vallès (Barcelona)

 

De: Brandon Castellano ***@***.***> 
Enviado el: dissabte, 2 de juliol de 2022 0:19
Para: Breakthrough/DVR-Scan ***@***.***>
CC: angelferre ***@***.***>; Mention ***@***.***>
Asunto: Re: [Breakthrough/DVR-Scan] Motion file has bigger size than original (#42)

 

In v1.5, there will be an option to use ffmpeg for generating output files. This allows you to both do re-encoding (-m ffmpeg) as well as codec copying (-m copy), e.g.:

dvr-scan -i video.mp4 -m ffmpeg
dvr-scan -i video.mp4 -m copy

You can configure the encoder arguments passed to ffmpeg by using a config file (the default is to use x264).

Note that certain features will not work in this mode yet (mainly, any overlays, and concatenating multiple input videos). Support for these features with these modes can be considered if required by filing a new feature request.

Thanks!

**Comment by Breakthrough** [comment]
Hi Angel;

I will try to get a beta version out for early testing within the next week or so, and hope to make the final v1.5 release later this month.

Thanks!

**Comment by angelferre** [comment]
Thank you very much!! Hope it works, it is great news!

 



 



 

Angel Ferre Giménez

General Manager

M:      +34 627 48 25 20 

E:        ***@***.***> ***@***.*** 

@Sant Cugat Business Park

Av. Via Augusta, 15-25

08174 Sant Cugat del Vallès (Barcelona)

 

De: Brandon Castellano ***@***.***> 
Enviado el: dilluns, 4 de juliol de 2022 0:06
Para: Breakthrough/DVR-Scan ***@***.***>
CC: angelferre ***@***.***>; Mention ***@***.***>
Asunto: Re: [Breakthrough/DVR-Scan] Motion file has bigger size than original (#42)

 

Hi Angel;

I will try to get a beta version out for early testing within the next week or so, and hope to make the final v1.5 release later this month.

Thanks!

**Comment by Breakthrough** [comment]
Hi @angelferre v1.5 is now officially released, looking forward to any feedback you may have.  Best regards!
