### ISSUE TITLE
Windows binary location

### ISSUE THREAD

**Issue by ElmarJongerius** [Breakthrough/DVR-Scan#43]
I have been using the binary executable of DVR-scan for a few months, and after moving to a new PC I'm trying to get the binary again.

When downloading any of the sources I cannot find it and I'm sure it should be somewhere, but I cannot locate it.

The binary gives me enough options and I'm really glad to use it.  For now I'll use the old binary, but when following the documentation doesn't lead me to it.

**Comment by Breakthrough** [comment]
Hi @ElmarJongerius;

I recently re-published the binaries, they were removed in v1.1 but I decided to add them back.  Until the documentation has been updated, you can grab a copy for v1.1 from [the v1.1 release page](https://github.com/Breakthrough/DVR-Scan/releases/tag/v1.1).

Thanks!

**Comment by Breakthrough** [comment]
Closing as duplicate of #32.
