### ISSUE TITLE
Specify the input.

### ISSUE THREAD

**Issue by mickeymickey123** [Breakthrough/DVR-Scan#44]
I'm new to python, can someone please give me an example of specify the input "-i" in the syntax. 
Thank you

**Comment by Breakthrough** [comment]
Hi @mickeymickey123;

You can see the documentation for the CLI here:
https://dvr-scan.readthedocs.io/en/latest/guide/examples/

Invoking DVR-Scan can be done as:

`dvr-scan -i some_video.mp4`

Thanks!
