### ISSUE TITLE
Downscale factor has no effect

### ISSUE THREAD

**Issue by Breakthrough** [Breakthrough/DVR-Scan#46]
Currently, downscale factor has no effect if set (i.e. is wholly unused).  If set, also needs to re-calculate the kernel size appropriately, and ensure ROI selection is not affected (but scales properly).

Discovered while refactoring ScanContext as part of #33.

**Comment by Breakthrough** [comment]
Resolved in v1.2 branch, to be included in next release of DVR-Scan.

**Comment by ocram** [comment]
> If set, also needs to re-calculate the kernel size appropriately, and ensure ROI selection is not affected (but scales properly).

Has this (specifically, the first part) actually been implemented?

From the commit above, it seems the kernel size is only re-calculated automatically for implicit (automatically used) values, i.e. when you provide no explicit kernel size yourself. Maybe that’s all that is desired here. But what this means is that whenever you provide a kernel size and then change the downscale factor, it stops working as expected, and you have to adjust the kernel size manually again (to match the changed downscale factor).

As an example, if I start with `--downscale-factor 1 --kernel-size 15` and then switch to …

 * `--downscale-factor 2`, I need to manually re-adjust to `--kernel-size 7`
 * `--downscale-factor 4`, I need to manually re-adjust to `--kernel-size 3`
 * `--downscale-factor 8`, I need to manually re-adjust to `--kernel-size 3` (minimum reached?)

… for roughly equal results. Is this intended?

**Comment by Breakthrough** [comment]
Ah very good catch - this is not intended indeed.  Will re-open this until it's fixed, thank you for the update!

**Comment by Breakthrough** [comment]
Fixed in v1.4 branch, will be included in next release of DVR-Scan.  Thanks @ocram!
