### ISSUE TITLE
Processed 0 frames

### ISSUE THREAD

**Issue by myscho15** [Breakthrough/DVR-Scan#56]
Hay, i have problem, i need analyze low resolution video, but dvr scan didnt work. Can anyone help me. In video file are movements, i think is problem with resolution. I try setup --kernel size, kernel size alway is fail :-(

This is from command line: [DVR-Scan] Initializing scan context...
[DVR-Scan] Opened video skuska2.avi (640 x 480 at 25.016 FPS).
[DVR-Scan] Appended video skuska2.avi.
[DVR-Scan] Scanning input video for motion events...
[DVR-Scan] Processed: 0 frames [00:00, ? frames/s]
[DVR-Scan] Processed 0 frames read in 0.1 secs (avg 0.0 FPS).
[DVR-Scan] No motion events detected in input.

EDIT: i check codec of my file is MJPEG (MJPG) i mean this is the problem. I recode video with VLC to another format and it works but my file is 1,5 GB big (30minutes) with good quality images and details, after recoding to another format quality goes down, its possible to "learn" DVR SCAN to can read my video files? Thank you very much.

Thank all.

**Comment by Breakthrough** [comment]
Hi @myscho15;

It looks like the - character in your command is a different character for
some reason.  Try typing out the command manually instead of copying and
pasting and see if that helps, or try copying `-k 1`.

This is what I see on my screen looking at your message:
[image: image.png]

Clearly, the dash is a strange character infront of the `k`, unlike `o`
(they are not the same width).

Let me know if this resolves the issue!

**Comment by myscho15** [comment]
> Hi @myscho15; It looks like the - character in your command is a different character for some reason. Try typing out the command manually instead of copying and pasting and see if that helps, or try copying `-k 1`. I'm also not sure why it doesn't work with mjpeg, that should be compatible with OpenCV. Can you share a small sample of the file? Thanks!

Hay, my fault with this command, i misspelld, now its work but i must convert my videos before analyzing.

Yes how i can you sent?

**Comment by Breakthrough** [comment]
You can now attach files to Github issues (in most cases you can drag-and-drop them into your browser window).  Thanks!
