### ISSUE TITLE
Only scan specific time interval?

### ISSUE THREAD

**Issue by hpacleb** [Breakthrough/DVR-Scan#60]
I'm not sure if there's a command for this already but I haven't seen it in the docs. If not, I think this would be a great feature to have. 
Currently, if I only want to scan a specific interval of the video (eg. 30 minutes - 1 hour) to save some CPU processing time, I would need to clip the video and use the clipped video instead of the original one. Would love to have it as a parameter instead so I wouldn't have to clip any video again.

**Comment by Breakthrough** [comment]
Sorry totally forgot this exists... I should update the documentation though.

`-st` / `--start-time`
`-dt` / `--duration`
`-et` / `--end-time`

Run --help for a complete list.  Thanks!

**Comment by Breakthrough** [comment]
@darmbrust seeking is still unoptimized but I've filed #92 just now to track it for an upcoming version (likely will work on that for v1.6).  Feel free to add any more comments there (or upload any examples if possible).

If you need to do this for a lot of files, you can try using `ffmpeg`'s codec copying mode by creating a temporary file:

    ffmpeg -ss 05:00:00 -i video.mp4 -c:v copy out.mp4
