### ISSUE TITLE
Docs have incorrect long string for -roi (--region-of-interest should read --rectangle-of-interest)

### ISSUE THREAD

**Issue by chibbert** [Breakthrough/DVR-Scan#63]
Documentation has: 

`-roi / **--region-of-interest**: If specified, scans only in the selected rectangular area. Can select with mouse, or by specifying a bounding box of the form [x y w h] (e.g. -roi allows specifying the bounding box with mouse, and -roi 100 110 50 75 specify a bounding box starting at (100,110) with a width and height of 50x75 pixels). Selection is made with the mouse by clicking-and-dragging, followed by hitting the enter/return key when the selection is finalized.`

But the long version of -roi should be:
`--rectangle-of-interest`

**Comment by Breakthrough** [comment]
Thanks for fixing that up @chibbert.
