### ISSUE TITLE
Erroneously saying “Scan-only mode specified” every time although video output is written

### ISSUE THREAD

**Issue by ocram** [Breakthrough/DVR-Scan#66]
For me, a basic command like

```
dvr-scan --input "my-input-video.mp4" --output "my-output-video.avi"
```

causes the text output on the CLI to say “Scan-only mode specified, list of motion events” (after completion), even though that option has obviously not been specified. The output file is written correctly, so it’s just superfluous text output, I guess. Not even annoying, but still incorrect (apparently).

```
[DVR-Scan] Processed 30766 frames read in 1473.5 secs (avg 20.9 FPS).
[DVR-Scan] Detected 1 motion events in input.
[DVR-Scan] Scan-only mode specified, list of motion events:
-------------------------------------------------------------
|   Event #    |  Start Time  |   Duration   |   End Time   |
-------------------------------------------------------------
|  Event    1  |  00:06:16.8  |  00:00:04.5  |  00:06:21.3  |
-------------------------------------------------------------
[DVR-Scan] Comma-separated timecode values:
00:06:16.833,00:06:21.300
[DVR-Scan] Motion events written to disk.
```

DVR-Scan: v1.3 (latest release)
Python: v3.5.1
cv2: v4.2.0
numpy: v1.18.5
OS: Ubuntu 20.04
pip source: `https://bootstrap.pypa.io/pip/3.5/get-pip.py`

**Comment by Breakthrough** [comment]
Completed and ready for inclusion in v1.4 release.
