### ISSUE TITLE
Cannot find video source.

### ISSUE THREAD

**Issue by TasGeo** [Breakthrough/DVR-Scan#8]
Hello,

I am using windows 10 home.

I have OpenCV  on my system; the location of it is this PC/windows (c:).

However, every time I try to scan for any of my videos, it comes up with cannot find video source, which includes my AVI, MP4 and WMV files.

**Comment by Breakthrough** [comment]
Hi @TasGeo;

Can you provide some additional details?  What version of OpenCV are you using?  Are you using the standalone version of DVR-Scan, or did you install it from source?

Thank you.

**Comment by Breakthrough** [comment]
Closing issue until more information can be provided to assist with triaging.  Feel free to reopen the issue or create a new one when you are able to do so.
