### ISSUE TITLE
can't find output

### ISSUE THREAD

**Issue by celmi** [Breakthrough/DVR-Scan#87]
Hello. Sorry, total noob-question, but I'm unable to locate any output. Where am I supposed to find it? And how could I have answered this question myself, without having to ask for help?
Many thanks for your support!

p.s. and if you know, how I could have formatted this output-text better, I'd be glad to learn. Somehow this editor seems to mis-interpret this text as markup, even when within code-marking.

```
C:\Users\CEL>dvr-scan -i "C:\c_tmp_downloads\Wärmebildkamera\2_Zeit 22.07-22.27.mp4"
[DVR-Scan] Initializing scan context...
[DVR-Scan] Opened video 2_Zeit 22.07-22.27.mp4 (1024 x 768 at 24.582 FPS).
[DVR-Scan] Appended video 2_Zeit 22.07-22.27.mp4.
[DVR-Scan] Scanning input video for motion events...
[DVR-Scan] Processed:  30%|██████████████▋                                  | 8861/29523 [00:57<02:05, 164.39 frames/s][h264 @ 000002be34f7fa80] error while decoding MB 17 46, bytestream -5
[DVR-Scan] Processed:  75%|████████████████████████████████████            | 22207/29523 [02:26<00:47, 154.81 frames/s][h264 @ 000002be34f21b80] error while decoding MB 36 36, bytestream -21
[DVR-Scan] Processed: 100%|███████████████████████████████████████████████▉| 29491/29523 [03:16<00:00, 163.48 frames/s][DVR-Scan] Failed to decode 6 frame(s) from video, result may be incorrect. Try re-encoding or remuxing video (e.g. ffmpeg -i video.mp4 -c:v copy out.mp4). See https://github.com/Breakthrough/DVR-Scan/issues/62 for details.
[DVR-Scan] Processed: 100%|███████████████████████████████████████████████▉| 29499/29523 [03:16<00:00, 149.80 frames/s]
[DVR-Scan] Processed 29499 frames read in 197.0 secs (avg 149.7 FPS).
[DVR-Scan] Detected 30 motion events in input.
[DVR-Scan] List of motion events:
-------------------------------------------------------------
|   Event #    |  Start Time  |   Duration   |   End Time   |
-------------------------------------------------------------
|  Event    1  |  00:00:00.0  |  00:00:04.3  |  00:00:04.3  |
|  Event    2  |  00:00:27.0  |  00:00:03.6  |  00:00:30.6  |
|  Event    3  |  00:00:33.3  |  00:00:03.9  |  00:00:37.1  |
|  Event    4  |  00:00:39.2  |  00:00:03.7  |  00:00:42.8  |
|  Event    5  |  00:02:06.2  |  00:00:04.9  |  00:02:11.0  |
|  Event    6  |  00:02:55.0  |  00:00:03.6  |  00:02:58.5  |
|  Event    7  |  00:05:26.8  |  00:00:03.6  |  00:05:30.4  |
|  Event    8  |  00:06:47.7  |  00:00:03.8  |  00:06:51.5  |
|  Event    9  |  00:06:51.6  |  00:00:03.1  |  00:06:54.7  |
|  Event   10  |  00:07:10.6  |  00:00:05.3  |  00:07:15.8  |
|  Event   11  |  00:07:22.2  |  00:00:04.0  |  00:07:26.1  |
|  Event   12  |  00:08:02.1  |  00:00:03.7  |  00:08:05.8  |
|  Event   13  |  00:08:08.6  |  00:00:03.5  |  00:08:05.8  |
|  Event   14  |  00:08:23.4  |  00:00:05.8  |  00:08:29.2  |
|  Event   15  |  00:09:44.3  |  00:00:03.7  |  00:09:47.9  |
|  Event   16  |  00:10:01.6  |  00:00:03.6  |  00:10:05.2  |
|  Event   17  |  00:10:05.2  |  00:00:02.8  |  00:10:05.2  |
|  Event   18  |  00:11:37.1  |  00:00:04.0  |  00:11:41.0  |
|  Event   19  |  00:11:51.8  |  00:00:04.8  |  00:11:56.5  |
|  Event   20  |  00:12:12.3  |  00:00:04.6  |  00:12:16.9  |
|  Event   21  |  00:13:53.1  |  00:00:03.6  |  00:13:56.6  |
|  Event   22  |  00:15:02.0  |  00:00:03.5  |  00:13:56.6  |
|  Event   23  |  00:15:33.9  |  00:00:06.2  |  00:15:40.0  |
|  Event   24  |  00:16:36.5  |  00:00:04.0  |  00:16:40.5  |
|  Event   25  |  00:16:45.7  |  00:00:03.9  |  00:16:49.5  |
|  Event   26  |  00:16:49.8  |  00:00:04.5  |  00:16:54.3  |
|  Event   27  |  00:16:54.3  |  00:00:05.6  |  00:16:59.9  |
|  Event   28  |  00:17:05.7  |  00:00:03.5  |  00:16:59.9  |
|  Event   29  |  00:17:14.6  |  00:00:05.2  |  00:17:19.8  |
|  Event   30  |  00:19:34.0  |  00:00:03.9  |  00:19:37.9  |
-------------------------------------------------------------
[DVR-Scan] Comma-separated timecode values:
00:00:00.041,00:00:04.271,00:00:27.012,00:00:30.592,00:00:33.277,00:00:37.101,00:00:39.216,00:00:42.837,00:02:06.192,00:02:11.033,00:02:54.968,00:02:58.508,00:05:26.830,00:05:30.410,00:06:47.744,00:06:51.528,00:06:51.568,00:06:54.660,00:07:10.566,00:07:15.814,00:07:22.160,00:07:26.106,00:08:02.150,00:08:05.770,00:08:08.618,00:08:05.770,00:08:23.426,00:08:29.162,00:09:44.299,00:09:47.920,00:10:01.629,00:10:05.209,00:10:05.250,00:10:05.209,00:11:37.067,00:11:41.013,00:11:51.793,00:11:56.512,00:12:12.296,00:12:16.853,00:13:53.063,00:13:56.602,00:15:02.017,00:13:56.602,00:15:33.870,00:15:40.013,00:16:36.519,00:16:40.465,00:16:45.672,00:16:49.536,00:16:49.821,00:16:54.255,00:16:54.337,00:16:59.910,00:17:05.727,00:16:59.910,00:17:14.636,00:17:19.844,00:19:34.050,00:19:37.914
[DVR-Scan] Motion events written to disk. 
```

**Comment by celmi** [comment]
I've tried now linux too, but same result: dvr-scan says "...written to disk" but I just can't find it :(

**Comment by Breakthrough** [comment]
Hi @celmi;

You can put code between ``` marks to have it appear unformatted, I've modified your original post so you can take a look to see how it was done.  Motion events should be written to the current working directory, so in the first logs you sent, they should appear in `C:\Users\CEL`.  Do they not appear there for you?

If they don't appear in the current working directory, would you be willing to try [DVR-Scan v1.5-beta](https://github.com/Breakthrough/DVR-Scan/releases/tag/v1.5-beta) and see if you have the same issue?  With v1.5, you can also set the output folder (using `-d`) as well as get debug logs (`--verbosity debug`).

Hope this helps, let me know if you make any progress!

**Comment by celmi** [comment]
Great, thank you so much for this patient response.
Yes, the files are where you said they should be. As a noob so I would have expected the working directory would be where my mp4 file was. I should look up the concept of a working directory :)
I actually did try to check the --help page beforehand and also checked the online-manual for the keyword "output". So I think your investment in documentation will pay off in the long run.
Cheers

p.s. thanks also for the formatting help. I had tried to use the <> - Button of the editor, but  that inserts only two of those quotation marks instead of three as needed. That's a bit odd, isn't it? (I know you're not responsible for this editor).

**Comment by Breakthrough** [comment]
Glad everything is working as expected.

I will add an FAQ entry for this in the v1.5 documentation, and also include the word "output" to make it easier for others to find.  It's important to get feedback like this, as if something is unclear for someone, others will also have the same question in the future.  Many thanks for the report.

--------------------------------------------------

TODOs:
 - [ ] Add FAQ entry
 - [ ] Update quickstart text to include "output files"
 - [x] Ensure CLI documents this behaviour (done, documented as part of `-d`/`--output-directory` flag)

--------------------------------------------------

P.S. I see what you mean now about the editor.  By default it only inserts single backquotes for `inline code`. If you select multiple lines and then press the <> button, it will insert three backquotes around the selected text.
