### ISSUE TITLE
numbering of video clips does not correspond to event-number

### ISSUE THREAD

**Issue by celmi** [Breakthrough/DVR-Scan#88]
The numbering of events in the commandline-output starts at 1 (event 1, event 2, etc.) while the exported videoclips start at number 0 (0000, 0001, 0002).

This miss-match makes it a bit tedious, if one wishes to work with both, the table of events in the command-line and the videos.

I would suggest that videos too should start their numbering with 0001, or "event0001".
In my usecase it would also be useful if the videos-name would include the start-time (eg. "event0001at00-00-04")

**Comment by Breakthrough** [comment]
Good catch, I realize now I actually fixed this in v1.5 when I was refactoring things, so marking this as in progress (it should be documented in the changelog still).  As for your second point, I will file a new tracking issue for customizing output file names using a template.  Thanks for the report!

TODO:

 - [ ] Document this change in the changelog for v1.5
