### ISSUE TITLE
Motion Detection Problem found in DVR-Scan

### ISSUE THREAD

**Issue by kzyokzyo** [Breakthrough/DVR-Scan#9]
Dear all,
  I use two video stream (H.264) format to do the motion detection using DVR-scan but I meet the problem as shown below:

One of the Execute Commands:
e.g. dvr-scan -i C:\motionDetection\P180309_134916_135923.avi -o C:\motionDetection\P180309_134916_135923_video_motion_only.avi

Problems:
1. non-existing PPS 0 referenced
2. decode_slice_header error
3. missing picture in access unit with size n = 8, 10 or 20

I am worried about the above problems can affect the motion detection accuracy although it can output all motion events in a single video with less false alarm using DVR-scan default setting

Could you tell me the operation is normal or abnormal. Please help me. Thanks a lot for your help!

**Comment by Breakthrough** [comment]
Hi @kzyokzyo;

Is it possible that the video stream was corrupted?  Have you experienced this with other files?  If you re-encode the input file (e.g. using ffmpeg), do you experience the same result?

Any additional information you can provide, or even a sample, would be very helpful.

Thank you!

**Comment by wakeupwakeup** [comment]
I have the same mesages all the time with all my avi videos. It seems it works well but perhaps not detecting all movements?

[h264 @ 07516040] non-existing PPS 0 referenced
[h264 @ 07516040] decode_slice_header error
[h264 @ 07516040] no frame!

**Comment by Breakthrough** [comment]
Is it possible to share a sample video exhibiting this error?  (You can now upload video files to Github issues!)

Thanks!

**Comment by Breakthrough** [comment]
Closing until a sample can be provided for analysis.
