### ISSUE TITLE
Support deprecated PTX architectures in CUDA builds

### ISSUE THREAD

**Issue by sundeepgoel72** [Breakthrough/DVR-Scan#97]
The current CUDA version does not support older NVIDIA GPU (i have a GTX 750 TI). 

Could support for the same be added. I would be happy to try and build the required libraries / dll - but will need some guidance along the way .

Refer https://github.com/Breakthrough/DVR-Scan/issues/94 for additional details

Q: What kind of performance uplift should i expect over the current 300FPS am able to achieve using MOG (with downsampling, and skipping 4 frame) without CUDA ? This will help to determine if investing effort in creating dll / library is good value, or would it be better to invest in a new GPU.

**Comment by Breakthrough** [comment]
For anyone that wants to give this a try, I had followed James Bowley's guide here: https://jamesbowley.co.uk/build-opencv-with-cuda-in-windows/
Note that compiling OpenCV + CUDA support may take several hours, and will require tens of gigabytes of space due to the number of dependencies and temporary files required.

------------------------------------

Regarding performance, I still have yet to do any exhaustive benchmarks, but a quick test on my system (GTX 2070) using a 1080p video yields:

| Subtractor | Downsampling | Frame Skip | Processing Speed (Effective) | Speedup |
|---|---|---|---|--|
| MOG2 | None | None | 60 |  |
| MOG2_CUDA | None | None | 140 | 2.33x |
| MOG2 | 2 | 2 | 330 | |
| MOG2_CUDA | 2 | 2 | 460 | 1.4x |

Using CUDA with DVR-Scan is not particularily well optimized yet (see #12 for some background).  Typically I see less than 10% GPU utilization, so it will likely perform just as well on older GPU models currently.  As per #12, there are some significant technical issues limiting better GPU utilization, much of which I suspect comes down to using Python to interact with OpenCV/CUDA via FFI/cytpes.  There are also some opportunities to use the GPU for video decoding as well, but I am not sure how robust the GPU decoder is given the variety of video formats most users have.

**Comment by sundeepgoel72** [comment]
I think i may have managed to get openCV working with CUDA using binaries from https://jamesbowley.co.uk/downloads/#OpenCV4.5.0. 

A further install of cudnn was needed, which was done from here : https://developer.nvidia.com/rdp/cudnn-download

Am able to run most of the pre-built exes, with GTC 750 Ti being detected, and GPU usage spiking on execution.

How do I get DVR-Scan to use this version to open-cv ?

**Comment by Breakthrough** [comment]
First, uninstall any version of DVR-Scan and install it using `pip` (e.g. `pip install dvr_scan`).  Next, ensure you have the OpenCV Python module installed, e.g. `python -c "import cv2"` should execute without failing.  Lastly, ensure you built OpenCV correctly, and that `-b MOG2_CUDA` will be supported:

    python -c "import dvr_scan; assert dvr_scan.motion_detector.MotionDetectorCudaMOG2.is_available()"

If those commands execute correctly, then you can run `dvr-scan` with `-b MOG2_CUDA`.  Hope this helps!

**Comment by sundeepgoel72** [comment]
> If those commands execute correctly, then you can run `dvr-scan` with `-b MOG2_CUDA`. Hope this helps!

I have been able to execute "python -c "import dvr_scan; assert dvr_scan.motion_detector.MotionDetectorCudaMOG2.is_available()" without an error. 

Have also uninstalled DVR-Scan from Windows.

Can i execute directly from a windows batch, or will I need to write a python script to use DVR-Scan now ?

**Comment by sundeepgoel72** [comment]
I validated the opencv cuda install by running opencv_perf_cudaarithm.exe --gtest_filter=Sz_Type_Flags_GEMM.GEMM/29 as per validation step on https://jamesbowley.co.uk/accelerate-opencv-4-5-0-on-windows-build-with-cuda-and-python-bindings/#cuda_performance

result
Device 0: "NVIDIA GeForce GTX 750 Ti"
  CUDA Driver Version / Runtime Version          11.70 / 11.10
  CUDA Capability Major/Minor version number:    5.0
  Total amount of global memory:                 2048 MBytes (2147221504 bytes)
  GPU Clock Speed:                               1.11 GHz
  Max Texture Dimension Size (x,y,z)             1D=(65536), 2D=(65536,65536), 3D=(4096,4096,4096)
  Max Layered Texture Size (dim) x layers        1D=(16384) x 2048, 2D=(16384,16384) x 2048
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per block:           1024
  Maximum sizes of each dimension of a block:    1024 x 1024 x 64
  Maximum sizes of each dimension of a grid:     2147483647 x 65535 x 65535
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and execution:                 Yes with 4 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Concurrent kernel execution:                   Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support enabled:                No
  Device is using TCC driver mode:               No
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Bus ID / PCI location ID:           1 / 0
  Compute Mode:
      Default (multiple host threads can use ::cudaSetDevice() with device simultaneously)

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version  = 11.70, CUDA Runtime Version = 11.10, NumDevs = 1

Basis above, the openCV with CUDA seems to be properly installed and running fine.

I also did the other steps for the python biding as per : https://jamesbowley.co.uk/accelerate-opencv-4-5-0-on-windows-build-with-cuda-and-python-bindings/#python_bindings. 

python -c "import cv2; print(f'OpenCV: {cv2.__version__} for python installed and working')" is executing fine 
did the other steps for DVR-Scan install via pip, however, getting error:-
C:\sg-bin\opencv_4_5_0_cuda_11_1_py38\install\x64\vc16\bin>dvr-scan -b mog2_cuda -i e:\surveillance\Ch1\2020-10-24\ch1-20201024000110_20201024000148.mp4
[DVR-Scan] DVR-Scan v1.5.1
[DVR-Scan] Method MOG2_CUDA is not available. To enable it, install a version of the OpenCV package `cv2` that includes support for it, or download the experimental CUDA-enabled build: https://dvr-scan.readthedocs.io/.

**Comment by Breakthrough** [comment]
When you compile a Python module, it must match the Python version you want to run it on.  The filename of the module you have, `cv2.cp38-win_amd64.pyd`, is for Python 3.8 (`cp38`) on Windows 64-bit (`win_amd64`).  Try using Python 3.8 x64 instead and see if that resolves the issue.

**Comment by sundeepgoel72** [comment]
> Try using Python 3.8 x64 instead and see if that resolves the issue.

uninstalled 3.10, and did a fresh install of 3.8. Now getting following error after copying the pyd to the site-packages folder:-
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: DLL load failed while importing cv2: The specified module could not be found. At least the error has changed :-)

**Comment by sundeepgoel72** [comment]
Tried many so called "solutions" from the net, nothing worked !!! :-(
Now trying using anaconda since most examples of a working version seem to be using it.

**Comment by sundeepgoel72** [comment]
> Tried many so called "solutions" from the net, nothing worked !!! :-(
> Now trying using anaconda since most examples of a working version seem to be using it.

Voila, finally it WORKED!!!!  
Fix was to 
1. install anaconda
2. create environment for version 3.8 
3. the cv2.cp38-win_amd64.pyd into site-packages directory of the 3.8 environment
4. install dvr-scan

its finally working, a bit disappoint though. I was expecting much improved performance - but seems slower than the normal python install. 
MOG2 on normal python getting slightly better FPS vs with MOG2_CUDA using anaconda. probably a performance issue on the ananconda side, since it seems very "heavy".

More investigations tomorrow !!!1

**Comment by sundeepgoel72** [comment]
Fix was to 
1. install anaconda
2. create environment for version 3.8 
3. the cv2.cp38-win_amd64.pyd into site-packages directory of the 3.8 environment
4. install dvr-scan
